#! /usr/bin/env bash

REMOTE_TAG=$(curl \
  --silent \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/wasm3/wasm3/releases?per_page=1 \
  | awk '/"tag_name"\s*:\s*"/' \
  | grep -oE "v([0-9]{1,}\.{0,1})+")

LOCAL_TAG=$(cat VERSION | tr -d '[:space:]')

if [[ "$REMOTE_TAG" > "$LOCAL_TAG" ]]; then
  echo "$REMOTE_TAG is newer than $LOCAL_TAG"
  echo "Updating to $REMOTE_TAG..."

  rm -rf .wasm3
  mkdir .wasm3
  pushd .wasm3 > /dev/null

  git clone --depth 1 --branch $REMOTE_TAG https://github.com/wasm3/wasm3.git &> /dev/null

  find wasm3/source -regex ".*\.c" -exec cp {} ../Sources/CWasm3/ \;
  find wasm3/source | grep -E "source/(m3|was).*\.h" | xargs -I INPUT_FILE cp INPUT_FILE ../Sources/CWasm3/include/
  rm ../Sources/CWasm3/include/m3.h # remove this deprecated header

  popd > /dev/null

  echo $REMOTE_TAG > VERSION

  echo "Updated to $REMOTE_TAG"
else
  echo "$LOCAL_TAG is most recent version"
fi

